stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - xmux
  image: python:3-alpine
  before_script:
    - pip install mkdocs mkdocs-material > /dev/null
  script:
    - mkdocs build
  artifacts:
    expire_in: 1 hour
    paths:
      - ./site

deploy:
  stage: deploy
  tags:
    - xmux
  image: andreysenov/firebase-tools:7.6.1
  script:
    - firebase deploy --project xmux-app --token "$FIREBASE_TOKEN" --only hosting:xmux-docs
