name: Deploy to Firebase

on:
  push:
    branches:
      - release

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip3 install setuptools wheel
          pip3 install mkdocs mkdocs-material pygments
      - name: Build
        run: python3 -m mkdocs build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Website
          path: site
  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Website
          path: Website
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting:xmux-docs
        env:
          PROJECT_ID: xmux-app
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
