name: Deploy

on:
  push:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: pip3 install mkdocs mkdocs-material
      - name: Build
        run: mkdocs build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: site
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: site
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting:xmux-docs
        env:
          PROJECT_ID: xmux-app
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
